from __future__ import annotations

import sys
from pathlib import Path


SILVER_TRANSFORM_DIR = Path(__file__).resolve().parents[2] / "transform" / "silver"
if str(SILVER_TRANSFORM_DIR) not in sys.path:
    sys.path.insert(0, str(SILVER_TRANSFORM_DIR))

import build_silver_boxscore_player_game as player_game_silver
import build_silver_boxscore_team_game as team_game_silver
import build_silver_boxscore_matchups as matchups_silver


def test_boxscore_player_game_schema_order_matches_databricks_contract():
    assert player_game_silver.TARGET_SCHEMA.names == [
        "gameId",
        "teamId",
        "team_side",
        "personId",
        "name",
        "nameI",
        "firstName",
        "familyName",
        "jerseyNum",
        "position",
        "status",
        "order",
        "starter",
        "oncourt",
        "played",
        "minutes",
        "minutesCalculated",
        "plus",
        "minus",
        "plusMinusPoints",
        "assists",
        "blocks",
        "blocksReceived",
        "fieldGoalsAttempted",
        "fieldGoalsMade",
        "foulsOffensive",
        "foulsDrawn",
        "foulsPersonal",
        "foulsTechnical",
        "freeThrowsAttempted",
        "freeThrowsMade",
        "reboundsDefensive",
        "reboundsOffensive",
        "reboundsTotal",
        "steals",
        "turnovers",
        "points",
        "threePointersAttempted",
        "threePointersMade",
        "twoPointersAttempted",
        "twoPointersMade",
        "pointsFastBreak",
        "pointsInThePaint",
        "pointsSecondChance",
        "fieldGoalsPercentage",
        "freeThrowsPercentage",
        "threePointersPercentage",
        "twoPointersPercentage",
        "_meta_pipeline_run_id",
        "_meta_ingested_at_utc",
        "_meta_source_system",
        "_meta_source_key",
        "_meta_source_last_modified_utc",
        "_meta_schema_version",
    ]


def test_boxscore_team_game_schema_order_matches_databricks_contract():
    assert team_game_silver.TARGET_SCHEMA.names == [
        "gameId",
        "team_side",
        "teamId",
        "teamName",
        "teamCity",
        "teamTricode",
        "score",
        "inBonus",
        "timeoutsRemaining",
        "assists",
        "benchPoints",
        "biggestLead",
        "biggestScoringRun",
        "blocks",
        "blocksReceived",
        "fastBreakPointsAttempted",
        "fastBreakPointsMade",
        "fieldGoalsAttempted",
        "fieldGoalsMade",
        "foulsDrawn",
        "foulsOffensive",
        "foulsPersonal",
        "foulsTeam",
        "foulsTeamTechnical",
        "foulsTechnical",
        "freeThrowsAttempted",
        "freeThrowsMade",
        "leadChanges",
        "points",
        "pointsAgainst",
        "pointsFastBreak",
        "pointsFromTurnovers",
        "pointsInThePaint",
        "pointsInThePaintAttempted",
        "pointsInThePaintMade",
        "pointsSecondChance",
        "reboundsDefensive",
        "reboundsOffensive",
        "reboundsPersonal",
        "reboundsTeam",
        "reboundsTeamDefensive",
        "reboundsTeamOffensive",
        "reboundsTotal",
        "secondChancePointsAttempted",
        "secondChancePointsMade",
        "steals",
        "teamFieldGoalAttempts",
        "threePointersAttempted",
        "threePointersMade",
        "timesTied",
        "turnovers",
        "turnoversTeam",
        "turnoversTotal",
        "twoPointersAttempted",
        "twoPointersMade",
        "assistsTurnoverRatio",
        "fastBreakPointsPercentage",
        "fieldGoalsEffectiveAdjusted",
        "fieldGoalsPercentage",
        "freeThrowsPercentage",
        "pointsInThePaintPercentage",
        "secondChancePointsPercentage",
        "threePointersPercentage",
        "trueShootingAttempts",
        "trueShootingPercentage",
        "twoPointersPercentage",
        "biggestLeadScore",
        "biggestScoringRunScore",
        "minutes",
        "minutesCalculated",
        "timeLeading",
        "_meta_pipeline_run_id",
        "_meta_ingested_at_utc",
        "_meta_source_system",
        "_meta_source_key",
        "_meta_source_last_modified_utc",
        "_meta_schema_version",
    ]


def test_boxscore_matchups_schema_order_matches_silver_contract():
    assert matchups_silver.TARGET_SCHEMA.names == [
        "game_id",
        "away_team_id",
        "home_team_id",
        "team_side",
        "team_id",
        "team_name",
        "team_city",
        "team_tricode",
        "team_slug",
        "person_id",
        "first_name",
        "family_name",
        "name_i",
        "player_slug",
        "position",
        "comment",
        "jersey_num",
        "matchups_person_id",
        "matchups_first_name",
        "matchups_family_name",
        "matchups_name_i",
        "matchups_player_slug",
        "matchups_jersey_num",
        "matchup_minutes",
        "matchup_minutes_sort",
        "partial_possessions",
        "percentage_defender_total_time",
        "percentage_offensive_total_time",
        "percentage_total_time_both_on",
        "switches_on",
        "player_points",
        "team_points",
        "matchup_assists",
        "matchup_potential_assists",
        "matchup_turnovers",
        "matchup_blocks",
        "matchup_field_goals_made",
        "matchup_field_goals_attempted",
        "matchup_field_goals_percentage",
        "matchup_three_pointers_made",
        "matchup_three_pointers_attempted",
        "matchup_three_pointers_percentage",
        "help_blocks",
        "help_field_goals_made",
        "help_field_goals_attempted",
        "help_field_goals_percentage",
        "matchup_free_throws_made",
        "matchup_free_throws_attempted",
        "shooting_fouls",
        "_meta_pipeline_run_id",
        "_meta_ingested_at_utc",
        "_meta_source_system",
        "_meta_source_key",
        "_meta_source_last_modified_utc",
        "_meta_schema_version",
    ]
