from __future__ import annotations

import sys
from pathlib import Path


SILVER_TRANSFORM_DIR = Path(__file__).resolve().parents[2] / "transform" / "silver"
if str(SILVER_TRANSFORM_DIR) not in sys.path:
    sys.path.insert(0, str(SILVER_TRANSFORM_DIR))

import build_silver_boxscore_player_game as player_game_silver
import build_silver_boxscore_team_game as team_game_silver


def test_boxscore_player_game_schema_order_matches_databricks_contract():
    assert player_game_silver.TARGET_SCHEMA.names == [
        "gameId",
        "teamId",
        "team_side",
        "personId",
        "name",
        "nameI",
        "firstName",
        "familyName",
        "jerseyNum",
        "position",
        "status",
        "order",
        "starter",
        "oncourt",
        "played",
        "minutes",
        "minutesCalculated",
        "plus",
        "minus",
        "plusMinusPoints",
        "assists",
        "blocks",
        "blocksReceived",
        "fieldGoalsAttempted",
        "fieldGoalsMade",
        "foulsOffensive",
        "foulsDrawn",
        "foulsPersonal",
        "foulsTechnical",
        "freeThrowsAttempted",
        "freeThrowsMade",
        "reboundsDefensive",
        "reboundsOffensive",
        "reboundsTotal",
        "steals",
        "turnovers",
        "points",
        "threePointersAttempted",
        "threePointersMade",
        "twoPointersAttempted",
        "twoPointersMade",
        "pointsFastBreak",
        "pointsInThePaint",
        "pointsSecondChance",
        "fieldGoalsPercentage",
        "freeThrowsPercentage",
        "threePointersPercentage",
        "twoPointersPercentage",
        "_meta_pipeline_run_id",
        "_meta_ingested_at_utc",
        "_meta_source_system",
        "_meta_source_key",
        "_meta_source_last_modified_utc",
        "_meta_schema_version",
    ]


def test_boxscore_team_game_schema_order_matches_databricks_contract():
    assert team_game_silver.TARGET_SCHEMA.names == [
        "gameId",
        "team_side",
        "teamId",
        "teamName",
        "teamCity",
        "teamTricode",
        "score",
        "inBonus",
        "timeoutsRemaining",
        "assists",
        "benchPoints",
        "biggestLead",
        "biggestScoringRun",
        "blocks",
        "blocksReceived",
        "fastBreakPointsAttempted",
        "fastBreakPointsMade",
        "fieldGoalsAttempted",
        "fieldGoalsMade",
        "foulsDrawn",
        "foulsOffensive",
        "foulsPersonal",
        "foulsTeam",
        "foulsTeamTechnical",
        "foulsTechnical",
        "freeThrowsAttempted",
        "freeThrowsMade",
        "leadChanges",
        "points",
        "pointsAgainst",
        "pointsFastBreak",
        "pointsFromTurnovers",
        "pointsInThePaint",
        "pointsInThePaintAttempted",
        "pointsInThePaintMade",
        "pointsSecondChance",
        "reboundsDefensive",
        "reboundsOffensive",
        "reboundsPersonal",
        "reboundsTeam",
        "reboundsTeamDefensive",
        "reboundsTeamOffensive",
        "reboundsTotal",
        "secondChancePointsAttempted",
        "secondChancePointsMade",
        "steals",
        "teamFieldGoalAttempts",
        "threePointersAttempted",
        "threePointersMade",
        "timesTied",
        "turnovers",
        "turnoversTeam",
        "turnoversTotal",
        "twoPointersAttempted",
        "twoPointersMade",
        "assistsTurnoverRatio",
        "fastBreakPointsPercentage",
        "fieldGoalsEffectiveAdjusted",
        "fieldGoalsPercentage",
        "freeThrowsPercentage",
        "pointsInThePaintPercentage",
        "secondChancePointsPercentage",
        "threePointersPercentage",
        "trueShootingAttempts",
        "trueShootingPercentage",
        "twoPointersPercentage",
        "biggestLeadScore",
        "biggestScoringRunScore",
        "minutes",
        "minutesCalculated",
        "timeLeading",
        "_meta_pipeline_run_id",
        "_meta_ingested_at_utc",
        "_meta_source_system",
        "_meta_source_key",
        "_meta_source_last_modified_utc",
        "_meta_schema_version",
    ]
